# Generated by Django 4.1 on 2022-10-02 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('link_count', models.IntegerField(default=0, verbose_name='количество ссылок')),
                ('subs_type', models.CharField(choices=[('REG', 'REGISTERED'), ('BTEST', 'BETA TESTER'), ('MOD', 'MODERATOR')], db_index=True, max_length=50, verbose_name='тип подписки')),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('violations', models.IntegerField(default=0, verbose_name='количество нарушений')),
                ('trust', models.BooleanField(default=False, verbose_name='доверенный пользователь')),
                ('username', models.CharField(max_length=50, null=True, verbose_name='имя')),
                ('company_name', models.CharField(max_length=100, null=True, verbose_name='компания')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='статус активации')),
                ('send_stat_email', models.BooleanField(db_index=True, default=False, verbose_name='Отправлять статистику')),
                ('my_timezone', models.CharField(choices=[('-12', '-12'), ('-11', '-11'), ('-10', '-10'), ('-9', '-9'), ('-8', '-8'), ('-7', '-7'), ('-6', '-6'), ('-5', '-5'), ('-4', '-4'), ('-3', '-3'), ('-2', '-2'), ('-1', '-1'), ('+0', '+0'), ('+1', '+1'), ('+2', '+2'), ('+3', '+3'), ('+4', '+4'), ('+5', '+5'), ('+6', '+6'), ('+7', '+7'), ('+8', '+8'), ('+9', '+9'), ('+10', '+10'), ('+11', '+11'), ('+12', '+12')], db_index=True, default='+0', max_length=3, verbose_name='Смещение по UTC')),
                ('is_staff', models.BooleanField(default=False, verbose_name='админ')),
                ('date_join', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата регистрации')),
                ('banned', models.BooleanField(default=False, verbose_name='Бан')),
                ('public_key', models.CharField(db_index=True, default='0000000000', max_length=25)),
                ('trust_rating', models.IntegerField(default=100000, null=True, verbose_name='Рейтинг доверия')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
