# Generated by Django 4.1 on 2022-10-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="my_timezone",
            field=models.CharField(
                choices=[
                    ("-12", "-12"),
                    ("-11", "-11"),
                    ("-10", "-10"),
                    ("-09", "-9"),
                    ("-08", "-8"),
                    ("-07", "-7"),
                    ("-06", "-6"),
                    ("-05", "-5"),
                    ("-04", "-4"),
                    ("-03", "-3"),
                    ("-02", "-2"),
                    ("-01", "-1"),
                    ("+00", "+0"),
                    ("+01", "+1"),
                    ("+02", "+2"),
                    ("+03", "+3"),
                    ("+04", "+4"),
                    ("+05", "+5"),
                    ("+06", "+6"),
                    ("+07", "+7"),
                    ("+08", "+8"),
                    ("+09", "+9"),
                    ("+10", "+10"),
                    ("+11", "+11"),
                    ("+12", "+12"),
                ],
                db_index=True,
                default="+0",
                max_length=3,
                verbose_name="Смещение по UTC",
            ),
        ),
    ]
