# Generated by Django 4.1 on 2022-08-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="subs_type",
            field=models.CharField(
                choices=[
                    ("REG", "REGISTERED"),
                    ("BTEST", "BETA TESTER"),
                    ("MOD", "MODERATOR"),
                ],
                db_index=True,
                max_length=50,
                verbose_name="тип подписки",
            ),
        ),
    ]
