# Generated by Django 4.1 on 2022-08-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_subs_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="send_stat_email",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="статус активации"
            ),
        ),
    ]
