# Generated by Django 4.1 on 2022-10-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_my_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="my_timezone",
            field=models.CharField(
                choices=[
                    ("-12", "-12"),
                    ("-11", "-11"),
                    ("-10", "-10"),
                    ("-09", "-09"),
                    ("-08", "-08"),
                    ("-07", "-07"),
                    ("-06", "-06"),
                    ("-05", "-05"),
                    ("-04", "-04"),
                    ("-03", "-03"),
                    ("-02", "-02"),
                    ("-01", "-01"),
                    ("+00", "+00"),
                    ("+01", "+01"),
                    ("+02", "+02"),
                    ("+03", "+03"),
                    ("+04", "+04"),
                    ("+05", "+05"),
                    ("+06", "+06"),
                    ("+07", "+07"),
                    ("+08", "+08"),
                    ("+09", "+09"),
                    ("+10", "+10"),
                    ("+11", "+11"),
                    ("+12", "+12"),
                ],
                db_index=True,
                default="+0",
                max_length=3,
                verbose_name="Смещение по UTC",
            ),
        ),
    ]
