# Generated by Django 3.2 on 2022-07-28 03:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220728_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_join',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 3, 45, 3, 384420, tzinfo=utc)),
        ),
    ]
