# Generated by Django 4.1 on 2022-10-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_my_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="my_timezone",
            field=models.CharField(
                choices=[
                    ("-12", "-12"),
                    ("-11", "-11"),
                    ("-10", "-10"),
                    ("-9", "-09"),
                    ("-8", "-08"),
                    ("-7", "-07"),
                    ("-6", "-06"),
                    ("-5", "-05"),
                    ("-4", "-04"),
                    ("-3", "-03"),
                    ("-2", "-02"),
                    ("-1", "-01"),
                    ("+0", "+00"),
                    ("+1", "+01"),
                    ("+2", "+02"),
                    ("+3", "+03"),
                    ("+4", "+04"),
                    ("+5", "+05"),
                    ("+6", "+06"),
                    ("+7", "+07"),
                    ("+8", "+08"),
                    ("+9", "+09"),
                    ("+10", "+10"),
                    ("+11", "+11"),
                    ("+12", "+12"),
                ],
                db_index=True,
                default="+0",
                max_length=3,
                verbose_name="Смещение по UTC",
            ),
        ),
    ]
