# Generated by Django 3.2 on 2022-07-28 07:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_date_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(max_length=100, null=True, verbose_name='компания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_join',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 7, 17, 22, 725504, tzinfo=utc), verbose_name='дата регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='статус активации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='админ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='link_count',
            field=models.IntegerField(default=0, verbose_name='количество ссылок'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subs_type',
            field=models.CharField(choices=[('REG', 'REGISTERED'), ('BTEST', 'BETA TESTER'), ('MOD', 'MODERATOR')], max_length=50, verbose_name='тип подписки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='trust',
            field=models.BooleanField(default=False, verbose_name='доверенный пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, null=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='violations',
            field=models.IntegerField(default=0, verbose_name='количество нарушений'),
        ),
    ]
