# Generated by Django 4.1 on 2022-09-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_my_timezone_alter_user_public_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="my_timezone",
            field=models.CharField(
                choices=[
                    ("-12", "-12"),
                    ("-11", "-11"),
                    ("-10", "-10"),
                    ("-12", "-9"),
                    ("-12", "-8"),
                    ("-12", "-7"),
                    ("-12", "-6"),
                    ("-12", "-5"),
                    ("-12", "-4"),
                    ("-12", "-3"),
                    ("-12", "-2"),
                    ("-12", "-1"),
                    ("-12", "+0"),
                    ("-12", "+1"),
                    ("-12", "+2"),
                    ("-12", "+3"),
                    ("-12", "+4"),
                    ("-12", "+5"),
                    ("-12", "+6"),
                    ("-12", "+7"),
                    ("-12", "+8"),
                    ("-12", "+9"),
                    ("-12", "+10"),
                    ("-12", "+11"),
                    ("-12", "+12"),
                ],
                db_index=True,
                default="+0",
                max_length=3,
            ),
        ),
    ]
