# Generated by Django 3.2 on 2022-07-29 04:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220728_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_join',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 29, 4, 26, 3, 739644, tzinfo=utc), verbose_name='дата регистрации'),
        ),
    ]
