# Generated by Django 4.1 on 2022-09-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_my_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="my_timezone",
            field=models.CharField(
                choices=[
                    ("-12", "-12"),
                    ("-11", "-11"),
                    ("-10", "-10"),
                    ("-9", "-9"),
                    ("-8", "-8"),
                    ("-7", "-7"),
                    ("-6", "-6"),
                    ("-5", "-5"),
                    ("-4", "-4"),
                    ("-3", "-3"),
                    ("-2", "-2"),
                    ("-1", "-1"),
                    ("+0", "+0"),
                    ("+1", "+1"),
                    ("+2", "+2"),
                    ("+3", "+3"),
                    ("+4", "+4"),
                    ("+5", "+5"),
                    ("+6", "+6"),
                    ("+7", "+7"),
                    ("+8", "+8"),
                    ("+9", "+9"),
                    ("+10", "+10"),
                    ("+11", "+11"),
                    ("+12", "+12"),
                ],
                db_index=True,
                default="+0",
                max_length=3,
            ),
        ),
    ]
