# Generated by Django 4.1 on 2022-09-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_my_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='banned',
            field=models.BooleanField(default=False, verbose_name='Бан'),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_timezone',
            field=models.CharField(choices=[('-12', '-12'), ('-11', '-11'), ('-10', '-10'), ('-9', '-9'), ('-8', '-8'), ('-7', '-7'), ('-6', '-6'), ('-5', '-5'), ('-4', '-4'), ('-3', '-3'), ('-2', '-2'), ('-1', '-1'), ('+0', '+0'), ('+1', '+1'), ('+2', '+2'), ('+3', '+3'), ('+4', '+4'), ('+5', '+5'), ('+6', '+6'), ('+7', '+7'), ('+8', '+8'), ('+9', '+9'), ('+10', '+10'), ('+11', '+11'), ('+12', '+12')], db_index=True, default='+0', max_length=3, verbose_name='Смещение по UTC'),
        ),
        migrations.AlterField(
            model_name='user',
            name='send_stat_email',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Отправлять статистику'),
        ),
        migrations.AlterField(
            model_name='user',
            name='trust',
            field=models.BooleanField(default=False, verbose_name='доверенный пользователь\n(снимает многие ограничения и проверки)'),
        ),
    ]
