# Generated by Django 3.2 on 2022-08-01 04:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_date_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_join',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 1, 4, 0, 26, 347511, tzinfo=utc), verbose_name='дата регистрации'),
        ),
    ]
