# Generated by Django 3.2 on 2022-08-06 09:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_date_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_join',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 6, 9, 0, 42, 721644, tzinfo=utc), verbose_name='дата регистрации'),
        ),
    ]
