# Generated by Django 3.2 on 2022-08-06 09:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220806_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_join',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 6, 9, 20, 7, 691233, tzinfo=utc), verbose_name='дата регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='public_key',
            field=models.CharField(db_index=True, default=0, max_length=25),
        ),
    ]
