# Generated by Django 3.2 on 2022-08-06 09:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220806_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_join',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 6, 9, 41, 35, 743752, tzinfo=utc), verbose_name='дата регистрации'),
        ),
    ]
