version: '3.3'


services:
  redis_db:
    image: redis
    command: redis-server --requirepass 'GsM10zWmoscow95'
    restart: always
    ports:
      - 6379:6379

  postgres_db:
    image: postgres:14.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres_db
      - redis_db
    env_file:
      - .env
    ports:
      - 8000:8000
  

volumes:
  postgres_data:
  celery_data: