version: '3.3'


services:
  redis_db:
    image: redis
    command: redis-server --requirepass 'GsM10zWmoscow95'
    restart: always
    ports:
      - 6379:6379

  postgres_db:
    image: postgres:14.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres_db
      - redis_db
    env_file:
      - .env
      
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
  
  flower:
    image: mher/flower
    environment:
    - CELERY_BROKER_URL=redis://:GsM10zWmoscow95@redis_db:6379/2
    - FLOWER_PORT=8888
    ports:  
      - 8888:8888
    depends_on:
      - web
      - redis_db

  

volumes:
  postgres_data:
  celery_data: