version: '3.3'


services:
  redis_db:
    image: redis
    command: redis-server --requirepass ''
    restart: always
    ports:
      - 6379:6379

  postgres_db:
    image: postgres:14.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432

volumes:
  postgres_data:
