# Generated by Django 3.2 on 2022-07-28 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elink_index', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkreguser',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Ссылки от зарегестрированных пользователей'},
        ),
        migrations.AlterField(
            model_name='infolink',
            name='link_check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_link', to='elink_index.linkreguser'),
        ),
        migrations.AlterField(
            model_name='linkreguser',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_link', to=settings.AUTH_USER_MODEL),
        ),
    ]
