# Generated by Django 3.2 on 2022-08-16 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elink_index', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infolink',
            options={'ordering': ['-date_check']},
        ),
        migrations.AlterModelOptions(
            name='linkreguser',
            options={'ordering': ['-date_add'], 'verbose_name_plural': 'Ссылки от зарегестрированных пользователей'},
        ),
    ]
