# Generated by Django 3.2 on 2022-07-28 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elink_index', '0003_auto_20220728_0629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkreguser',
            options={'ordering': ['date_add'], 'verbose_name_plural': 'Ссылки от зарегестрированных пользователей'},
        ),
    ]
