# Generated by Django 4.1 on 2022-09-03 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elink_index", "0005_linkreguser_qr"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="infolink",
            options={},
        ),
    ]
